# Generated by Django 4.2 on 2023-04-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_screening'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Django',
        ),
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='film',
            new_name='django',
        ),
        migrations.AlterField(
            model_name='screening',
            name='theater',
            field=models.CharField(choices=[('P', 'Pantheon'), ('W', 'Worlds Theater'), ('R', 'Regal Cinemas')], default='P', max_length=1, verbose_name='theater'),
        ),
    ]
