# Generated by Django 4.2 on 2023-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_film_django_alter_screening_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Video_Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='django',
            name='home_video_releases',
            field=models.ManyToManyField(to='main_app.home_video_release'),
        ),
    ]
